steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE}:${_TAG}', '.']
images:
- ${_IMAGE}:${_TAG}
substitutions:
  _IMAGE: gcr.io/instruqt/participant-host-bootstrap
  _TAG: latest
